volumes:
  localstack_data:
  postgres_data:



services:
  e2e_test_runner:
    build: .
    depends_on:
      contracts_builder:
        condition: service_completed_successfully
      migration_runner:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      anvil:
        condition: service_healthy
    working_dir: /account-abstraction
    volumes:
      - ../../:/account-abstraction
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ANVIL_RPC_URL=http://anvil:${ANVIL_PORT}
      - ANVIL_CHAIN_ID=${ANVIL_CHAIN_ID}
      - USE_KMS=false
      - PRIVATE_KEY=${SEOA_PRIVATE_KEY}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - BLOB_QUEUE_MESSAGE_GROUP_ID="aa-tx-sender-blob-queue"
      - STANDARD_QUEUE_MESSAGE_GROUP_ID="aa-tx-sender-standard-queue"
      - ANVIL_MNEMONIC=${ANVIL_MNEMONIC}
    command: ["cargo", "test", "-p", "e2e_test", "--features", "aws", "--", "--no-capture"]


  migration_runner:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /account-abstraction
    volumes:
      - ../../:/account-abstraction
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: ["cargo", "run", "-p", "migrator", "--bin", "migrate"]

  anvil:
    image: ghcr.io/foundry-rs/foundry
    platform: linux/amd64
    entrypoint: anvil
    command:
      [
        "--host", "0.0.0.0",
        "--port", "${ANVIL_PORT}",
        "--chain-id", "${ANVIL_CHAIN_ID}",
        "--mnemonic", "${ANVIL_MNEMONIC}",
        "--accounts", "1000",
        "--balance", "10000"
      ]
    ports:
      - "${ANVIL_PORT}:${ANVIL_PORT}"
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:${ANVIL_PORT}"]
      interval: 5s
      timeout: 3s
      retries: 5

  contracts_builder:
    build: .
    depends_on:
      anvil:
        condition: service_healthy
    working_dir: /account-abstraction/contracts
    volumes:
      - ../../:/account-abstraction
    command: ["sh", "-c", "npm i && npx hardhat run scripts/deployAndDelegate.ts --network anvilDocker"]

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
