version: "3.9"
services:
  hardhat:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
    command: npx hardhat node --hostname 0.0.0.0
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 1s
      retries: 5
      timeout: 1s

# Skandha screams when it's running against block 0
  hardhat_miner:
    image: curlimages/curl:latest
    depends_on:
      hardhat:
        condition: service_healthy
    entrypoint: >
      sh -c "
        curl -X POST http://hardhat:8545 \
          -H 'Content-Type: application/json' \
          -d '{
            \"jsonrpc\":\"2.0\",
            \"method\":\"evm_mine\",
            \"params\":[],
            \"id\":1
          }' > /dev/null;
        sleep 5
      "
    healthcheck:
      test: ["CMD", "curl", "-s", "http://hardhat:8545", "-H", "Content-Type: application/json", "-d", "'{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}' | grep 0x1"]
      interval: 1s
      retries: 5
      timeout: 1s

  skandha:
    image: etherspot/skandha:v2-latest
    depends_on:
      hardhat_miner:
        condition: service_healthy
    ports:
      - "14337:14337"
    volumes:
      - ./skandha-config.json:/usr/app/config.json:ro
    command: standalone --unsafeMode
      