Transform: AWS::Serverless-2016-10-31

Parameters:
  BlobSenderQueueMessageGroupId:
    Type: String
  MasterKmsSecretsName:
    Type: String
  LambdaFunctionRoleArn:
    Type: String
  DatabaseName:
    Type: String
  DbSecretsName:
    Type: String
  DatabaseAccessSecurityGroup:
    Type: String
  PrivateSubnets:
    Type: String
  BlobTxSenderQueueName:
    Type: String
  BlobTxSignerQueueName:
    Type: String
  BlobTxSignerDlqName:
    Type: String
  AaBlobBucketName:
    Type: String

Resources:
  BlobTxSignerDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref BlobTxSignerDlqName
      FifoQueue: true
      ContentBasedDeduplication: true

  BlobTxSignerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref BlobTxSignerQueueName
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 35
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BlobTxSignerDeadLetterQueue.Arn
        maxReceiveCount: 5

  BlobTxSignerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Handler: bootstrap
      CodeUri: ../../../target/lambda/aws_blob_tx_signer
      Timeout: 25
      Role: !Ref LambdaFunctionRoleArn
      Environment:
        Variables:
          DATABASE_URL: !Join
            - ""
            - - "postgresql://"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:username}}"
              - ":"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:password}}"
              - "@"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:host}}"
              - ":"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:port}}"
              - "/"
              - !Ref DatabaseName
          BLOB_SENDER_QUEUE_MESSAGE_GROUP_ID: !Ref BlobSenderQueueMessageGroupId
          BLOB_SENDER_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${BlobTxSenderQueueName}"
          BLOB_STORAGE_BUCKET_NAME: !Ref AaBlobBucketName
          USE_KMS: true
          SIGNER_KMS_ID: !Join
            - ""
            - - "{{resolve:secretsmanager:"
              - !Ref MasterKmsSecretsName
              - ":SecretString:AA_MASTER_KMS_ID}}"
      VpcConfig:
        SecurityGroupIds:
          - !Ref DatabaseAccessSecurityGroup
        SubnetIds: !Split [",", !Ref PrivateSubnets]
      Events:
        BlobTxSignerQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BlobTxSignerQueue.Arn
            BatchSize: 5
            FunctionResponseTypes:
              - ReportBatchItemFailures

Outputs:
  BlobTxSignerQueueArn:
    Description: ARN of the BlobTxSigner SQS queue
    Value: !GetAtt BlobTxSignerQueue.Arn

  BlobTxSignerQueueUrl:
    Description: URL of the BlobTxSigner SQS queue
    Value: !Ref BlobTxSignerQueue
