Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaFunctionRoleArn:
    Type: String
  DatabaseName:
    Type: String
  DbSecretsName:
    Type: String
  DatabaseAccessSecurityGroup:
    Type: String
  PrivateSubnets:
    Type: String
  RetryQueueName:
    Type: String
  RetryDlqName:
    Type: String

Resources:
  RetryDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref RetryDlqName
      FifoQueue: true
      ContentBasedDeduplication: true

  RetryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref RetryQueueName
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RetryDeadLetterQueue.Arn
        maxReceiveCount: 5

  RetryHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Handler: bootstrap
      CodeUri: ../../../target/lambda/aws_retry_handler
      Timeout: 300
      Role: !Ref LambdaFunctionRoleArn
      Environment:
        Variables:
          DATABASE_URL: !Join
            - ""
            - - "postgresql://"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:username}}"
              - ":"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:password}}"
              - "@"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:host}}"
              - ":"
              - "{{resolve:secretsmanager:"
              - !Ref DbSecretsName
              - ":SecretString:port}}"
              - "/"
              - !Ref DatabaseName
      VpcConfig:
        SecurityGroupIds:
          - !Ref DatabaseAccessSecurityGroup
        SubnetIds: !Split [",", !Ref PrivateSubnets]
      Events:
        RetryHandlerQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RetryQueue.Arn
            BatchSize: 5
            FunctionResponseTypes:
              - ReportBatchItemFailures
