version = 0.1

[dev.deploy.parameters]
stack_name = "aa-infra-dev"
region = "us-east-1"
s3_bucket = "ow-protocol-artifacts"
s3_prefix = "dev"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=dev",
    "AaBlobBucketName=aa-blob-bucket-dev",
    "DbSecretsName='/rev/dev/db-secret'",
    "MasterKmsSecretsName='/rev/dev/secrets'",
    "DatabaseName=account_abstraction_dev_db",
    "PrivateSubnets=/dev-stage/network/private-subnet-ids",
    "DatabaseAccessSecurityGroup=/dev/database/access-security-group-id",
    "OutcomeEventBusName=aa-dev-transaction-outcome-bus",
    "ReceiptPollerCleanupSchedulerRate='5 minutes'",

    "BlobTxSignerQueueName=aa-dev-blob-tx-signer.fifo",
    "BlobTxSignerDlqName=aa-dev-blob-tx-signer-dlq.fifo",

    "BlobTxSenderQueueName=aa-dev-blob-tx-sender.fifo",
    "BlobTxSenderDlqName=aa-dev-blob-tx-sender-dlq.fifo",

    "StandardTxSignerQueueName=aa-dev-standard-tx-signer.fifo",
    "StandardTxSignerDlqName=aa-dev-standard-tx-signer-dlq.fifo",

    "StandardTxSenderQueueName=aa-dev-standard-tx-sender.fifo",
    "StandardTxSenderDlqName=aa-dev-standard-tx-sender-dlq.fifo",

    "ReceiptPollerQueueName=aa-dev-receipt-poller.fifo",
    "ReceiptPollerDlqName=aa-dev-receipt-poller-dlq.fifo",

    "RetryQueueName=aa-dev-retry.fifo",
    "RetryDlqName=aa-dev-retry-dlq.fifo",
]

[stage.deploy.parameters]
stack_name = "aa-infra-stage"
region = "us-east-1"
s3_bucket = "ow-protocol-artifacts"
s3_prefix = "stage"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=stage",
    "AaBlobBucketName=aa-blob-bucket-stage",
    "DbSecretsName='/rev/stage/db-secret'",
    "MasterKmsSecretsName='/rev/stage/secrets'",
    "DatabaseName=account_abstraction_stage_db",
    "PrivateSubnets=/dev-stage/network/private-subnet-ids",
    "DatabaseAccessSecurityGroup=/stage/database/access-security-group-id",
    "OutcomeEventBusName=aa-stage-transaction-outcome-bus",
    "ReceiptPollerCleanupSchedulerRate='2 minutes'",

    "BlobTxSignerQueueName=aa-stage-blob-tx-signer.fifo",
    "BlobTxSignerDlqName=aa-stage-blob-tx-signer-dlq.fifo",

    "BlobTxSenderQueueName=aa-stage-blob-tx-sender.fifo",
    "BlobTxSenderDlqName=aa-stage-blob-tx-sender-dlq.fifo",

    "StandardTxSignerQueueName=aa-stage-standard-tx-signer.fifo",
    "StandardTxSignerDlqName=aa-stage-standard-tx-signer-dlq.fifo",

    "StandardTxSenderQueueName=aa-stage-standard-tx-sender.fifo",
    "StandardTxSenderDlqName=aa-stage-standard-tx-sender-dlq.fifo",

    "ReceiptPollerQueueName=aa-stage-receipt-poller.fifo",
    "ReceiptPollerDlqName=aa-stage-receipt-poller-dlq.fifo",

    "RetryQueueName=aa-stage-retry.fifo",
    "RetryDlqName=aa-stage-retry-dlq.fifo",
]

[prod.deploy.parameters]
stack_name = "aa-infra-prod"
region = "us-east-1"
s3_bucket = "ow-protocol-artifacts-prod"
s3_prefix = "prod"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=prod",
    "AaBlobBucketName=aa-blob-bucket-prod",
    "DbSecretsName='/rev/prod/db-secret'",
    "MasterKmsSecretsName='/rev/prod/secrets'",
    "DatabaseName=account_abstraction_prod_db",
    "PrivateSubnets=/prod/network/private-subnet-ids",
    "DatabaseAccessSecurityGroup=/prod/database/access-security-group-id",
    "OutcomeEventBusName=aa-prod-transaction-outcome-bus",
    "ReceiptPollerCleanupSchedulerRate='1 minute'",

    "BlobTxSignerQueueName=aa-prod-blob-tx-signer.fifo",
    "BlobTxSignerDlqName=aa-prod-blob-tx-signer-dlq.fifo",

    "BlobTxSenderQueueName=aa-prod-blob-tx-sender.fifo",
    "BlobTxSenderDlqName=aa-prod-blob-tx-sender-dlq.fifo",

    "StandardTxSignerQueueName=aa-prod-standard-tx-signer.fifo",
    "StandardTxSignerDlqName=aa-prod-standard-tx-signer-dlq.fifo",

    "StandardTxSenderQueueName=aa-prod-standard-tx-sender.fifo",
    "StandardTxSenderDlqName=aa-prod-standard-tx-sender-dlq.fifo",

    "ReceiptPollerQueueName=aa-prod-receipt-poller.fifo",
    "ReceiptPollerDlqName=aa-prod-receipt-poller-dlq.fifo",

    "RetryQueueName=aa-prod-retry.fifo",
    "RetryDlqName=aa-prod-retry-dlq.fifo",
]
