Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseName:
    Type: String
  DbSecretsName:
    Type: String
  MasterKmsSecretsName:
    Type: String
  AaBlobBucketName:
    Type: String
  PrivateSubnets:
    Type: AWS::SSM::Parameter::Value<String>
  DatabaseAccessSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
  StandardSenderQueueMessageGroupId:
    Type: String
    Default: standard-sender-queue-group
  ReceiptPollerQueueMessageGroupId:
    Type: String
    Default: receipt-poller-queue-group
  StandardTxSenderQueueName:
    Type: String
    Default: standard-tx-sender.fifo
  StandardTxSenderDlqName:
    Type: String
    Default: standard-tx-sender-dlq.fifo
  StandardTxSignerQueueName:
    Type: String
    Default: standard-tx-signer.fifo
  StandardTxSignerDlqName:
    Type: String
    Default: standard-tx-signer-dlq.fifo
  ReceiptPollerQueueName:
    Type: String
    Default: receipt-poller.fifo
  ReceiptPollerDlqName:
    Type: String
    Default: receipt-poller-dlq.fifo

Resources:
  AaBlobBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AaBlobBucketName

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SqsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ConsumeAaQueues
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                  - sqs:SendMessage
                Resource:
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSenderQueueName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSenderDlqName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSignerQueueName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSignerDlqName}"

        - PolicyName: KmsEthereumSigningAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: UseEthereumKmsKey
                Effect: Allow
                Action:
                  - kms:Sign
                  - kms:GetPublicKey
                Resource: "*"

  StandardTxSigner:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/standard-tx-signer.yml
      Parameters:
        StandardSenderQueueMessageGroupId: !Ref StandardSenderQueueMessageGroupId
        MasterKmsSecretsName: !Ref MasterKmsSecretsName
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DatabaseName: !Ref DatabaseName
        DbSecretsName: !Ref DbSecretsName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
        StandardTxSenderQueueName: !Ref StandardTxSenderQueueName
        StandardTxSignerQueueName: !Ref StandardTxSignerQueueName
        StandardTxSignerDlqName: !Ref StandardTxSignerDlqName

  StandardTxSender:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/standard-tx-sender.yml
      Parameters:
        StandardTxSenderQueueName: !Ref StandardTxSenderQueueName
        StandardTxSenderDlqName: !Ref StandardTxSenderDlqName
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DatabaseName: !Ref DatabaseName
        DbSecretsName: !Ref DbSecretsName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
        ReceiptPollerQueueMessageGroupId: !Ref ReceiptPollerQueueMessageGroupId
        ReceiptPollerQueueName: !Ref ReceiptPollerQueueName

  ReceiptPoller:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/receipt-poller.yml
      Parameters:
        ReceiptPollerQueueName: !Ref ReceiptPollerQueueName
        ReceiptPollerDlqName: !Ref ReceiptPollerDlqName

  Migrations:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/migrations.yml
      Parameters:
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DbSecretsName: !Ref DbSecretsName
        DatabaseName: !Ref DatabaseName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
