Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
  DatabaseName:
    Type: String
  DbSecretsName:
    Type: String
  MasterKmsSecretsName:
    Type: String
  AaBlobBucketName:
    Type: String
  PrivateSubnets:
    Type: AWS::SSM::Parameter::Value<String>
  DatabaseAccessSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>

  StandardTxSignerQueueName:
    Type: String
    Default: standard-tx-signer.fifo
  StandardTxSignerDlqName:
    Type: String
    Default: standard-tx-signer-dlq.fifo

  StandardSenderQueueMessageGroupId:
    Type: String
    Default: standard-sender-queue-group
  StandardTxSenderQueueName:
    Type: String
    Default: standard-tx-sender.fifo
  StandardTxSenderDlqName:
    Type: String
    Default: standard-tx-sender-dlq.fifo

  ReceiptPollerQueueMessageGroupId:
    Type: String
    Default: receipt-poller-queue-group
  ReceiptPollerQueueName:
    Type: String
    Default: receipt-poller.fifo
  ReceiptPollerDlqName:
    Type: String
    Default: receipt-poller-dlq.fifo
  ReceiptPollerCleanupSchedulerRate:
    Type: String
  ReceiptPollerQueueDelay:
    Type: Number
    Default: 15

  RetryQueueName:
    Type: String
    Default: aa-tx-retry.fifo
  RetryDlqName:
    Type: String
    Default: aa-tx-retry-dlq.fifo
  RetryQueueMessageGroupId:
    Type: String
    Default: retry-queue-group

  OutcomeEventBusName:
    Type: String

Resources:
  AaBlobBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AaBlobBucketName

  OutcomeEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref OutcomeEventBusName

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SqsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ConsumeAaQueues
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                  - sqs:SendMessage
                Resource:
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSenderQueueName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSenderDlqName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSignerQueueName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StandardTxSignerDlqName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${ReceiptPollerQueueName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${ReceiptPollerDlqName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${RetryQueueName}"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${RetryDlqName}"
        - PolicyName: KmsEthereumSigningAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: UseEthereumKmsKey
                Effect: Allow
                Action:
                  - kms:Sign
                  - kms:GetPublicKey
                Resource: "*"
        - PolicyName: OutcomeEventBusAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/${OutcomeEventBusName}"

  StandardTxSigner:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/standard-tx-signer.yml
      Parameters:
        StandardSenderQueueMessageGroupId: !Ref StandardSenderQueueMessageGroupId
        MasterKmsSecretsName: !Ref MasterKmsSecretsName
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DatabaseName: !Ref DatabaseName
        DbSecretsName: !Ref DbSecretsName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
        StandardTxSenderQueueName: !Ref StandardTxSenderQueueName
        StandardTxSignerQueueName: !Ref StandardTxSignerQueueName
        StandardTxSignerDlqName: !Ref StandardTxSignerDlqName

  StandardTxSender:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/standard-tx-sender.yml
      Parameters:
        StandardTxSenderQueueName: !Ref StandardTxSenderQueueName
        StandardTxSenderDlqName: !Ref StandardTxSenderDlqName
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DatabaseName: !Ref DatabaseName
        DbSecretsName: !Ref DbSecretsName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
        ReceiptPollerQueueMessageGroupId: !Ref ReceiptPollerQueueMessageGroupId
        ReceiptPollerQueueName: !Ref ReceiptPollerQueueName
        RetryQueueMessageGroupId: !Ref RetryQueueMessageGroupId
        RetryQueueName: !Ref RetryQueueName
        OutcomeEventBusName: !Ref OutcomeEventBusName

  ReceiptPoller:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/receipt-poller.yml
      Parameters:
        ReceiptPollerQueueName: !Ref ReceiptPollerQueueName
        ReceiptPollerDlqName: !Ref ReceiptPollerDlqName
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DatabaseName: !Ref DatabaseName
        DbSecretsName: !Ref DbSecretsName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
        RetryQueueMessageGroupId: !Ref RetryQueueMessageGroupId
        RetryQueueName: !Ref RetryQueueName
        ReceiptPollerQueueDelay: !Ref ReceiptPollerQueueDelay
        OutcomeEventBusName: !Ref OutcomeEventBusName
        ReceiptPollerCleanupSchedulerRate: !Ref ReceiptPollerCleanupSchedulerRate

  RetryHandler:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/retry-handler.yml
      Parameters:
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DatabaseName: !Ref DatabaseName
        DbSecretsName: !Ref DbSecretsName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets
        RetryDlqName: !Ref RetryDlqName
        RetryQueueName: !Ref RetryQueueName

  Migrations:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/migrations.yml
      Parameters:
        LambdaFunctionRoleArn: !GetAtt LambdaFunctionRole.Arn
        DbSecretsName: !Ref DbSecretsName
        DatabaseName: !Ref DatabaseName
        DatabaseAccessSecurityGroup: !Ref DatabaseAccessSecurityGroup
        PrivateSubnets: !Ref PrivateSubnets

  SsmParameters:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/ssm.yml
      Parameters:
        StandardTxSignerQueueUrl: !GetAtt StandardTxSigner.Outputs.StandardTxSignerQueueUrl
        StandardTxSignerQueueArn: !GetAtt StandardTxSigner.Outputs.StandardTxSignerQueueArn
        OutcomeEventBusName: !Ref OutcomeEventBusName
        Environment: !Ref Environment
